FROM node:24-alpine AS build
WORKDIR /app

ARG BASE_URL
ARG DATOCMS_API_READ_TOKEN
ARG DATOCMS_API_TOKEN
ARG POSTMARK_API_TOKEN
ARG PREVIEW_SECRET
ARG PIPEDRIVE_API_TOKEN
ARG PIPEDRIVE_API_URL
ARG AKISMET_API_TOKEN

ENV BASE_URL=$BASE_URL
ENV DATOCMS_API_READ_TOKEN=$DATOCMS_API_READ_TOKEN
ENV DATOCMS_API_TOKEN=$DATOCMS_API_TOKEN
ENV POSTMARK_API_TOKEN=$POSTMARK_API_TOKEN
ENV PREVIEW_SECRET=$PREVIEW_SECRET
ENV PIPEDRIVE_API_TOKEN=$PIPEDRIVE_API_TOKEN
ENV PIPEDRIVE_API_URL=$PIPEDRIVE_API_URL
ENV AKISMET_API_TOKEN=$AKISMET_API_TOKEN

COPY package*.json ./
RUN npm ci --ignore-scripts --no-audit --no-fund --no-update-notifier
COPY . .
RUN npm run build

FROM node:24-alpine AS runtime
WORKDIR /app

COPY --from=build /app/.output ./

ENV PORT=80
EXPOSE 80

CMD ["node", "server/index.mjs"]
