import type { Client } from "datocms/lib/cma-client-node";

/**
 * Migration 04: Create action_block, list_block, video_block, logo_grid,
 *               variable_block, icon_block, image_card_item
 *
 * Depends on:
 *  - phone_link, email_link (migration 02)
 *  - external_link (id=2034503), internal_link (id=2037919) — already exist
 *  - menu_item_internal, menu_item_external (migration 03) — but logo_grid
 *    items field is updated in migration 12 after those IDs are known;
 *    here we create logo_grid with an empty items validator, wired in mig 12.
 *  - list_item (id=42658) — already exists
 *  - variable model (migration 01) — must exist for variable_block
 *  - video_text_track model (migration 01) — must exist for video_block
 *
 * Because phone_link and email_link IDs are generated by migration 02,
 * we look them up by api_key here.
 */
export default async function (client: Client) {
  // Resolve IDs of dependencies by api_key
  const allTypes = await client.itemTypes.list();
  const byKey = (key: string) => {
    const t = allTypes.find((t) => t.api_key === key);
    if (!t) throw new Error(`item_type not found: ${key}`);
    return t.id;
  };

  const phoneLinkId = byKey("phone_link");
  const emailLinkId = byKey("email_link");
  const internalLinkId = "2037919"; // external_link already exists
  const externalLinkId = "2034503";
  const listItemId = "42658";
  const variableModelId = byKey("variable");
  const videoTrackModelId = byKey("video_text_track");

  // ── action_block ──────────────────────────────────────────────────────────
  console.log('Create block "Action Block" (action_block)');
  const actionBlock = await client.itemTypes.create(
    {
      name: "🎛️ Action Block",
      api_key: "action_block",
      modular_block: true,
      draft_saving_active: false,
      inverse_relationships_enabled: false,
    },
    { skip_menu_item_creation: true },
  );
  await client.fields.create(actionBlock.id, {
    label: "Items",
    field_type: "rich_text",
    api_key: "items",
    validators: {
      rich_text_blocks: { item_types: [phoneLinkId, internalLinkId, externalLinkId, emailLinkId] },
    },
    appearance: { addons: [], editor: "rich_text", parameters: { start_collapsed: false } },
    default_value: null,
  });
  console.log("action_block done:", actionBlock.id);

  // ── list_block ────────────────────────────────────────────────────────────
  console.log('Create block "List Block" (list_block)');
  const listBlock = await client.itemTypes.create(
    {
      name: "🔢 List Block",
      api_key: "list_block",
      modular_block: true,
      draft_saving_active: false,
      inverse_relationships_enabled: false,
    },
    { skip_menu_item_creation: true },
  );
  await client.fields.create(listBlock.id, {
    label: "Type",
    field_type: "string",
    api_key: "list_type",
    validators: { required: {} },
    appearance: {
      addons: [],
      editor: "string_select",
      parameters: {
        options: [
          { label: "Bullet", value: "bullet", hint: "" },
          { label: "Ordered", value: "ordered", hint: "" },
        ],
      },
    },
    default_value: "bullet",
  });
  await client.fields.create(listBlock.id, {
    label: "Start number",
    field_type: "integer",
    api_key: "start_number",
    hint: "Only used for Ordered lists.",
    validators: {},
    appearance: { addons: [], editor: "integer", parameters: { placeholder: null } },
    default_value: null,
  });
  await client.fields.create(listBlock.id, {
    label: "Items",
    field_type: "rich_text",
    api_key: "items",
    validators: { rich_text_blocks: { item_types: [listItemId] } },
    appearance: { addons: [], editor: "rich_text", parameters: { start_collapsed: false } },
    default_value: null,
  });
  console.log("list_block done:", listBlock.id);

  // ── video_block (uploaded video) ──────────────────────────────────────────
  console.log('Create block "Video Block" (video_block)');
  const videoBlock = await client.itemTypes.create(
    {
      name: "🎬 Video Block",
      api_key: "video_block",
      modular_block: true,
      draft_saving_active: false,
      inverse_relationships_enabled: false,
    },
    { skip_menu_item_creation: true },
  );
  await client.fields.create(videoBlock.id, {
    label: "Video",
    field_type: "file",
    api_key: "video_asset",
    validators: { required: {}, extension: { extensions: [], predefined_list: "video" } },
    appearance: { addons: [], editor: "file", parameters: {} },
    default_value: null,
  });
  await client.fields.create(videoBlock.id, {
    label: "Title",
    field_type: "string",
    api_key: "title",
    validators: {},
    appearance: { addons: [], editor: "single_line", parameters: { heading: false, placeholder: null } },
    default_value: null,
  });
  await client.fields.create(videoBlock.id, {
    label: "Autoplay",
    field_type: "boolean",
    api_key: "autoplay",
    validators: {},
    appearance: { addons: [], editor: "boolean", parameters: {} },
    default_value: null,
  });
  await client.fields.create(videoBlock.id, {
    label: "Mute",
    field_type: "boolean",
    api_key: "mute",
    validators: {},
    appearance: { addons: [], editor: "boolean", parameters: {} },
    default_value: null,
  });
  await client.fields.create(videoBlock.id, {
    label: "Loop",
    field_type: "boolean",
    api_key: "loop",
    validators: {},
    appearance: { addons: [], editor: "boolean", parameters: {} },
    default_value: null,
  });
  await client.fields.create(videoBlock.id, {
    label: "Tracks",
    field_type: "links",
    api_key: "tracks",
    validators: { items_item_type: { item_types: [videoTrackModelId] } },
    appearance: { addons: [], editor: "links_select", parameters: {} },
    default_value: null,
  });
  console.log("video_block done:", videoBlock.id);

  // ── logo_grid ─────────────────────────────────────────────────────────────
  console.log('Create block "Logo Grid" (logo_grid)');
  const logoGrid = await client.itemTypes.create(
    {
      name: "🏷️ Logo Grid",
      api_key: "logo_grid",
      modular_block: true,
      draft_saving_active: false,
      inverse_relationships_enabled: false,
    },
    { skip_menu_item_creation: true },
  );
  await client.fields.create(logoGrid.id, {
    label: "Title",
    field_type: "string",
    api_key: "title",
    validators: {},
    appearance: { addons: [], editor: "single_line", parameters: { heading: false, placeholder: null } },
    default_value: null,
  });
  // logos: rich_text referencing menu_item_internal + menu_item_external
  // (these IDs become known after migration 03, we wire in migration 12)
  await client.fields.create(logoGrid.id, {
    label: "Logos",
    field_type: "rich_text",
    api_key: "logos",
    hint: "Each logo is a menu item with an image. The image replaces the title when set.",
    validators: { rich_text_blocks: { item_types: [] } },
    appearance: { addons: [], editor: "rich_text", parameters: { start_collapsed: false } },
    default_value: null,
  });
  console.log("logo_grid done:", logoGrid.id);

  // ── variable_block (inline) ───────────────────────────────────────────────
  console.log('Create block "Variable Block" (variable_block)');
  const variableBlock = await client.itemTypes.create(
    {
      name: "🔣 Variable Block",
      api_key: "variable_block",
      modular_block: true,
      draft_saving_active: false,
      inverse_relationships_enabled: false,
    },
    { skip_menu_item_creation: true },
  );
  await client.fields.create(variableBlock.id, {
    label: "Variable",
    field_type: "link",
    api_key: "variable",
    validators: { required: {}, item_item_type: { item_types: [variableModelId] } },
    appearance: { addons: [], editor: "link_select", parameters: { filters: [] } },
    default_value: null,
  });
  console.log("variable_block done:", variableBlock.id);

  // ── icon_block (inline) ───────────────────────────────────────────────────
  console.log('Create block "Icon Block" (icon_block)');
  const iconBlock = await client.itemTypes.create(
    {
      name: "🚘 Icon Block",
      api_key: "icon_block",
      modular_block: true,
      draft_saving_active: false,
      inverse_relationships_enabled: false,
    },
    { skip_menu_item_creation: true },
  );
  await client.fields.create(iconBlock.id, {
    label: "Name",
    field_type: "string",
    api_key: "name",
    validators: { required: {} },
    appearance: { addons: [], editor: "single_line", parameters: { heading: false, placeholder: "icon-name" } },
    default_value: null,
  });
  await client.fields.create(iconBlock.id, {
    label: "Title",
    field_type: "string",
    api_key: "title",
    validators: {},
    appearance: { addons: [], editor: "single_line", parameters: { heading: false, placeholder: null } },
    default_value: null,
  });
  console.log("icon_block done:", iconBlock.id);

  console.log("✅ Action/list/video/logo/inline blocks created");
}
