query EventSlug($locale: SiteLocale, $slug: String) {
  page: event(locale: $locale, filter: { slug: { eq: $slug } }) {
    ...eventItem
  }
}

fragment eventItem on EventRecord {
  title
  slug
  seo {
    title
    description
    image {
      url
    }
  }
  headerIllustration {
    url
    alt
    width
    height
  }
  date
  url
  callToActionLabel
  image {
    url
    alt
    width
    height
  }
  tags {
    title
    slug
  }
  eventIsOnline
  onlineEventUrl
  location {
    title
    address
    postalCode
    city
    countryCode
  }
  price
  bodyBlocks {
    __typename
    ... on TextBlockRecord {
      id
      text {
        value
      }
    }
    ... on ImageBlockRecord {
      id
      caption
      captionPosition
      image {
        url
        alt
        width
        height
      }
    }
    ... on ActionBlockRecord {
      id
    }
  }
}
