query Blog(
  $locale: SiteLocale!
  $skip: IntType
  $first: IntType
  $tagFilter: LinksFilter
  $tagId: ItemId
) {
  page: page(locale: $locale, filter: { slug: { eq: "blog" } }) {
    title
    subtitle
    seo {
      title
      description
      image {
        url
        alt
        width
        height
      }
    }
  }
  items: allBlogPosts(
    first: $first
    skip: $skip
    locale: $locale
    orderBy: _firstPublishedAt_DESC
    filter: {
      isArchived: { eq: "false" }
      tags: $tagFilter
      _locales: { allIn: [$locale] }
    }
  ) {
    ...blogPost
  }
  itemsMeta: _allBlogPostsMeta(
    locale: $locale
    filter: {
      isArchived: { eq: "false" }
      tags: $tagFilter
      _locales: { allIn: [$locale] }
    }
  ) {
    count
  }
  tags: allTags(
    locale: $locale
    filter: { category: { eq: "topic" } }
  ) {
    id
    title
    slug
  }
  tag: tag(filter: { id: { eq: $tagId } }) {
    i18nSlugs: _allSlugLocales {
      locale
      value
    }
    id
    title
    slug
    description
    seo {
      title
      description
      image {
        id
        width
        height
        url
      }
    }
  }
}

fragment blogPost on BlogPostRecord {
  slug
  title
  date: _firstPublishedAt
  authors {
    name
    image {
      url
      alt
      width
      height
    }
  }
}
