name: Integration

on: 
  pull_request:
    branches: 
      - master

jobs:
  build:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run unit tests
      run: |
        npm install
        npm run test

